services:
  # RabbitMQ for AMQP
  rabbitmq:
    image: rabbitmq:3-management
    container_name: demo-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Eclipse Mosquitto for MQTT
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: demo-mosquitto
    ports:
      - "1883:1883"   # MQTT port
      - "9001:9001"   # WebSocket port
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  # Prosody for XMPP
  prosody:
    image: prosody/prosody:latest
    container_name: demo-prosody
    ports:
      - "5222:5222"   # XMPP client port
      - "5269:5269"   # XMPP server port
    environment:
      LOCAL: testuser
      DOMAIN: localhost
      PASSWORD: testpass
    volumes:
      - prosody_data:/var/lib/prosody
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
    command: prosody --config=/etc/prosody/prosody.cfg.lua

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: demo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Apache Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: demo-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"  # Enables KRaft mode
      KAFKA_PROCESS_ROLES: "controller,broker"  # This node acts as both controller and broker
      KAFKA_NODE_ID: 1  # Unique ID for this node
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"  # Controller quorum voters
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: '6228445f-2eb1-41be-b71c-f62578ed9939'  # Use a unique, consistent cluster ID
    volumes:
      - ./data:/var/lib/kafka/data

volumes:
  rabbitmq_data:
  prosody_data: